name: Build and Deploy Netflix Clone

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clean workspace
        run: |
          rm -rf *

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # or adopt / zulu depending on your preference

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifacts
          path: dist/

      - name: Deploy / Run
        run: |
          echo "Starting the Application..."
          npm install -g serve
          nohup serve -s dist -l 3000 &
          
      - name: Success Message
        if: success()
        run: echo "Pipeline executed successfully!"

      - name: Failure Message
        if: failure()
        run: echo "Pipeline failed!"
