name: Notify via Email

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  email-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a dummy job
      run: echo "Simulating job..."

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_APP_PASSWORD }}
        subject: GitHub Actions Build Notification
        to: sanskar.jain@galaxyweblinks.in
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          ✅ Build completed!

          🔹 Repository: ${{ github.repository }}
          🔹 Branch: ${{ github.ref_name }}
          🔹 Workflow: ${{ github.workflow }}
          🔹 Run ID: ${{ github.run_id }}
          🔹 Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

        attachments: |
          ./trivyfs.txt
          ./trivyimage.txt
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # SonarCloud
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # OWASP
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "MyProject"
        format: "ALL"
        out: "reports"

    # Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y

    - name: Trivy FS Scan
      run: trivy fs . > trivyfs.txt

    - name: Trivy Image Scan
      run: trivy image your-image:latest > trivyimage.txt

    # Upload all reports
    - name: Upload Scan Reports
      uses: actions/upload-artifact@v4
      with:
        name: scan-reports
        path: |
          reports
          trivyfs.txt
          trivyimage.txt