name: CI with SonarQube

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: http://<sonarqube-public-ip>:9000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install sonar-scanner
        run: |
          npm install -g sonar-scanner

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=Netflix \
            -Dsonar.projectName=Netflix \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      # Optional: Notification placeholder
      - name: Send Email on Completion (Optional)
        if: always()
        run: echo "Build finished. Setup SMTP notifications here if needed."
